<?php

namespace Database\Seeders;

use App\Models\Block;
use App\Models\CategoryBlock;
use App\Models\MainPageBlock;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class NewsSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'title_ar' => 'قسم التعليم الطبي',
                'title_en' => 'Medical Education Department',
                'description_ar' => 'الأستاذة أميمة حامد ، مديرة التعليم الطبي',
                'description_en' => 'Professor Omayma Hamed, Director of Medical Educat...',
                'content_ar' => '',
                'content_en' => '',
                'image_name' => 'news.jpg',
                'status' => true,
                'date' => today(),
                'created_at' => now(),
                'type' => Block::TYPE_NEWS,
            ],
            [
                'title_ar' => 'فريق المراجعيين يزور الكلية',
                'title_en' => 'NAQAAE audit team visited AFCM',
                'description_ar' => 'إستقبال كلية الطب بالقوات المسلحة فريق المراجعين م...',
                'description_en' => 'AFCM has received NAQAAE reviewer team visits both...',
                'content_ar' => '',
                'content_en' => '',
                'image_name' => 'news.jpg',
                'status' => true,
                'date' => today(),
                'created_at' => now(),
                'type' => Block::TYPE_NEWS,
            ],
            [
                'title_ar' => 'زيارة قطاع  خدمة المجتمع و تنمية البيئة  لمستشفي غ...',
                'title_en' => 'visit of Community service and environmental devel...',
                'description_ar' => 'مستشفي غمرة',
                'description_en' => 'Ghamra Hospital',
                'content_ar' => '',
                'content_en' => '',
                'image_name' => 'news.jpg',
                'status' => true,
                'date' => today(),
                'created_at' => now(),
                'type' => Block::TYPE_NEWS,
            ],
            [
                'title_ar' => 'وقعت كلية الطب بالقوات المسلحة (AFCM) وجامعة ولاية...',
                'title_en' => 'Armed Forces College of Medicine (AFCM) and Michig...',
                'description_ar' => 'قيم في التاسع من يناير 2018 تحت رعاية اللواء أيمن ...',
                'description_en' => 'It was held on 9th of JAN 2018 under patronage of ...',
                'content_ar' => '',
                'content_en' => '',
                'image_name' => 'news.jpg',
                'status' => true,
                'date' => today(),
                'created_at' => now(),
                'type' => Block::TYPE_NEWS,
            ],
            [
                'title_ar' => 'الاعلان عن قبول دفعة جديدة',
                'title_en' => 'Announcing Of Acceptance of a new batch of high sc...',
                'description_ar' => 'الفريق أول محمد زكي القائد العام للقوات المسلحة وز...',
                'description_en' => 'General Mohamed Zaki, Commander-in-Chief of the Ar...',
                'content_ar' => '',
                'content_en' => '',
                'image_name' => 'news.jpg',
                'status' => true,
                'date' => today(),
                'created_at' => now(),
                'type' => Block::TYPE_NEWS,
            ],
            [
                'title_ar' => 'فريق المراجعيين يزور الكلية',
                'title_en' => 'NAQAAE audit team visited AFCM',
                'description_ar' => 'إستقبال كلية الطب بالقوات المسلحة فريق المراجعين م...',
                'description_en' => 'AFCM has received NAQAAE reviewer team visits both...',
                'content_ar' => '',
                'content_en' => '',
                'image_name' => 'news.jpg',
                'status' => true,
                'date' => today(),
                'created_at' => now(),
                'type' => Block::TYPE_NEWS,
            ],
            [
                'title_ar' => 'وقعت كلية الطب بالقوات المسلحة (AFCM) وجامعة ولاية...',
                'title_en' => 'Armed Forces College of Medicine (AFCM) and Michig...',
                'description_ar' => 'قيم في التاسع من يناير 2018 تحت رعاية اللواء أيمن ...',
                'description_en' => 'It was held on 9th of JAN 2018 under patronage of ...',
                'content_ar' => '',
                'content_en' => '',
                'image_name' => 'news.jpg',
                'status' => true,
                'date' => today(),
                'created_at' => now(),
                'type' => Block::TYPE_NEWS,
            ],
            [
                'title_ar' => 'قسم التعليم الطبي',
                'title_en' => 'Medical Education Department',
                'description_ar' => 'الأستاذة أميمة حامد ، مديرة التعليم الطبي',
                'description_en' => 'Professor Omayma Hamed, Director of Medical Educat...',
                'content_ar' => '',
                'content_en' => '',
                'image_name' => 'news.jpg',
                'status' => true,
                'date' => today(),
                'created_at' => now(),
                'type' => Block::TYPE_NEWS,
            ],
            [
                'title_ar' => 'وقعت كلية الطب بالقوات المسلحة (AFCM) وجامعة ولاية...',
                'title_en' => 'Armed Forces College of Medicine (AFCM) and Michig...',
                'description_ar' => 'قيم في التاسع من يناير 2018 تحت رعاية اللواء أيمن ...',
                'description_en' => 'It was held on 9th of JAN 2018 under patronage of ...',
                'content_ar' => '',
                'content_en' => '',
                'image_name' => 'news.jpg',
                'status' => true,
                'date' => today(),
                'created_at' => now(),
                'type' => Block::TYPE_NEWS,
            ],
            [
                'title_ar' => 'فريق المراجعيين يزور الكلية',
                'title_en' => 'NAQAAE audit team visited AFCM',
                'description_ar' => 'إستقبال كلية الطب بالقوات المسلحة فريق المراجعين م...',
                'description_en' => 'AFCM has received NAQAAE reviewer team visits both...',
                'content_ar' => '',
                'content_en' => '',
                'image_name' => 'news.jpg',
                'status' => true,
                'date' => today(),
                'created_at' => now(),
                'type' => Block::TYPE_NEWS,
            ],
        ];
        Block::insert($data);

        $newData = [
            [
                'category_id' => 1,
                'block_id' => 16,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 2,
                'block_id' => 16,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 3,
                'block_id' => 16,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 4,
                'block_id' => 16,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

            [
                'category_id' => 1,
                'block_id' => 17,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 2,
                'block_id' => 17,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 3,
                'block_id' => 17,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 4,
                'block_id' => 17,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

            [
                'category_id' => 1,
                'block_id' => 19,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 2,
                'block_id' => 19,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 3,
                'block_id' => 19,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 4,
                'block_id' => 19,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

            [
                'category_id' => 1,
                'block_id' => 20,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 2,
                'block_id' => 20,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 3,
                'block_id' => 20,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 4,
                'block_id' => 20,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

            [
                'category_id' => 1,
                'block_id' => 21,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 2,
                'block_id' => 21,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 3,
                'block_id' => 21,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 4,
                'block_id' => 21,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

            [
                'category_id' => 1,
                'block_id' => 22,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 2,
                'block_id' => 22,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 3,
                'block_id' => 22,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 4,
                'block_id' => 22,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

            [
                'category_id' => 1,
                'block_id' => 23,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 2,
                'block_id' => 23,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 3,
                'block_id' => 23,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 4,
                'block_id' => 23,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

            [
                'category_id' => 1,
                'block_id' => 24,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 2,
                'block_id' => 24,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 3,
                'block_id' => 24,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 4,
                'block_id' => 24,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

            [
                'category_id' => 1,
                'block_id' => 25,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 2,
                'block_id' => 25,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 3,
                'block_id' => 25,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'category_id' => 4,
                'block_id' => 25,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
        ];


        CategoryBlock::insert($newData);

        $newData2 = [
            [
                'main_page_id' => 1,
                'block_id' => 16,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 2,
                'block_id' => 16,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 3,
                'block_id' => 16,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

            [
                'main_page_id' => 1,
                'block_id' => 17,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 2,
                'block_id' => 17,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 3,
                'block_id' => 17,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

            [
                'main_page_id' => 1,
                'block_id' => 18,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 2,
                'block_id' => 18,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 3,
                'block_id' => 18,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

            [
                'main_page_id' => 1,
                'block_id' => 19,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 2,
                'block_id' => 19,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 3,
                'block_id' => 19,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

            [
                'main_page_id' => 1,
                'block_id' => 20,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 2,
                'block_id' => 20,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 3,
                'block_id' => 20,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

            [
                'main_page_id' => 1,
                'block_id' => 21,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 2,
                'block_id' => 21,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 3,
                'block_id' => 21,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

            [
                'main_page_id' => 1,
                'block_id' => 22,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 2,
                'block_id' => 22,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 3,
                'block_id' => 22,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

            [
                'main_page_id' => 1,
                'block_id' => 23,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 2,
                'block_id' => 23,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 3,
                'block_id' => 23,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

            [
                'main_page_id' => 1,
                'block_id' => 24,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 2,
                'block_id' => 24,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 3,
                'block_id' => 24,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

            [
                'main_page_id' => 1,
                'block_id' => 25,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 2,
                'block_id' => 25,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],
            [
                'main_page_id' => 3,
                'block_id' => 25,
                'sort' => 1,
                'type' => Block::TYPE_NEWS,
                'date' => today(),
            ],

        ];

        MainPageBlock::insert($newData2);

    }
}
